language: d
sudo: false
dist: bionic


matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.095.0
  allow_failures:
    - d: dmd-nightly


addons:
  apt:
    packages:
      - libclang-dev
      - g++


install:
  - gem install bundler -v 1.17.3
  - bundle install


env:
  global:
    - LD_RUN_PATH=/usr/local/clang-7.0.0/lib


script:
  - ./ci.sh


after_success:
 - bash <(curl -s https://codecov.io/bash)
